import Footer from "@/sections/Footer/Footer";
import Gallery from "@/sections/Gallery/Gallery";
import GetInTouch from "@/sections/GetInTouch/GetInTouch";

import About from "@/sections/About/About";
import OurFacilities from "@/sections/OurFacilities/OurFacilities";
import WeProvided from "@/sections/WeProvided/WeProvided";
import Head from "next/head";
import Hero from "@/sections/Hero/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Hero />
        <About />
        <OurFacilities />
        <WeProvided />
        <Gallery />
        <GetInTouch />
        <Footer />
      </>
    </>
  );
}
